BEGIN;

CREATE SCHEMA IF NOT EXISTS event_logs;

CREATE TABLE IF NOT EXISTS event_logs.parsed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    student_id TEXT NOT NULL,
    class_code TEXT,
    event_ts TIMESTAMPTZ NOT NULL,
    event_type TEXT NOT NULL,
    program_type TEXT,
    playground TEXT,
    project_json JSONB,
    block_event_data_json JSONB,
    has_orphans BOOLEAN,
    switch_block_count INTEGER,
    error_message TEXT,
    source TEXT NOT NULL DEFAULT 'synthetic',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_parsed_events_event_type
    ON event_logs.parsed_events (event_type);

CREATE INDEX IF NOT EXISTS idx_parsed_events_session_ts
    ON event_logs.parsed_events (session_id, event_ts);

CREATE INDEX IF NOT EXISTS idx_parsed_events_student_ts
    ON event_logs.parsed_events (student_id, event_ts);

COMMIT;
