BEGIN;

CREATE TABLE IF NOT EXISTS event_logs.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    student_id TEXT NOT NULL,
    role TEXT NOT NULL,
    message_text TEXT NOT NULL,
    feedback_class TEXT,
    response_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_session_created_at
    ON event_logs.messages (session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_student_created_at
    ON event_logs.messages (student_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_response_id
    ON event_logs.messages (response_id);

COMMIT;
