BEGIN;

CREATE SCHEMA IF NOT EXISTS current_state;

CREATE TABLE IF NOT EXISTS current_state.state_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    student_id TEXT NOT NULL,
    time_on_task_s DOUBLE PRECISION NOT NULL,
    action_level TEXT NOT NULL,
    progress_pct DOUBLE PRECISION NOT NULL,
    direction TEXT NOT NULL,
    cognition TEXT NOT NULL,
    persistence TEXT NOT NULL,
    computed_from_event_id_min BIGINT,
    computed_from_event_id_max BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_state_snapshots_session_student UNIQUE (session_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_state_snapshots_student_created
    ON current_state.state_snapshots (student_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_state_snapshots_session_created
    ON current_state.state_snapshots (session_id, created_at DESC);

COMMIT;
