BEGIN;

CREATE TABLE IF NOT EXISTS event_logs.message_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES event_logs.messages (id) ON DELETE CASCADE,
    student_id TEXT NOT NULL,
    thumb TEXT NOT NULL CHECK (thumb IN ('up', 'down')),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_message_feedback_message_created_at
    ON event_logs.message_feedback (message_id, created_at);

CREATE INDEX IF NOT EXISTS idx_message_feedback_student_created_at
    ON event_logs.message_feedback (student_id, created_at);

COMMIT;
