AVAILABLE_BLOCKS = {
    "default": [],
    "GO-Mars": [
        "drive [forward/reverse]",
        "drive [forward/reverse] until [object/crash]",
        "drive [forward/reverse] for [number] [mm/inches]",
        "turn [right/left]",
        "turn [right/left] for [number] degrees",
        "turn to heading [number] degrees",
        "turn to rotation [number] degrees",
        "stop driving",
        "set drive velocity to [number] [%]",
        "set turn velocity to [number] [%]",
        "set drive heading to [number] degrees",
        "set drive rotation to [number] degrees",
        "set drive timeout to [number] seconds",
        "drive is done?",
        "drive is moving?",
        "drive heading in degrees",
        "drive rotation in degrees",
        "drive velocity in [%]",
        "spin [ArmMotor] [up/down]",
        "spin [ArmMotor] [up/down] for [number] [degrees/turns]",
        "spin [ArmMotor] to position [number] [degrees/turns]",
        "stop [ArmMotor]",
        "set [ArmMotor] velocity to [number] [%]",
        "set [ArmMotor] timeout to [number] seconds",
        "[ArmMotor] position in [degrees/turns]",
        "set [ArmMotor] position to [number] [degrees/turns]",
        "[ArmMotor] is done?",
        "[ArmMotor] is spinning?",
        "[ArmMotor] velocity in [%]",
        "[FrontEye] found an object?",
        "[FrontEye] detects [red/green/blue/orange/purple]?",
        "[FrontEye] brightness in %",
        "[FrontEye] hue in degrees",
        "detected crash?",
        "print [text/value]",
        "set cursor to next row",
        "clear all rows",
        "set print precision to [1/0.1/0.01/0.001/All Digits]",
        "wait [number] seconds",
        "wait until [condition]",
        "repeat [number]",
        "forever",
        "repeat until [condition]",
        "while [condition]",
        "if [condition] then",
        "if [condition] then else",
        "if [condition] then / else if [condition] then / else",
        "break",
        "stop project",
        "reset timer",
        "timer in seconds",
        "when timer > [number] seconds",
        "when started",
        "when I receive [my_event]",
        "broadcast [my_event]",
        "broadcast [my_event] and wait",
        "[a] [+] [b]",
        "[a] [=] [b]",
        "[condition] [and] [condition]",
        "not [condition]",
        "[a] [<] [b] [<] [c]",
        "pick random [a] to [b]",
        "round [number] to [number] decimal places",
        "[abs] of [number]",
        "atan2 of x: [number] y: [number]",
        "remainder of [a] / [b]",
        "join [text] [text]",
        "letter [number] of [text]",
        "length of [text]",
        "[text] contains [text]?",
        "convert [value] to [text]",
        "[myVariable]",
        "set [myVariable] to [number]",
        "change [myVariable] by [number]",
        "comment",
    ],
}


def resolve_available_blocks(playground: str) -> list[str]:
    return AVAILABLE_BLOCKS.get(playground, AVAILABLE_BLOCKS["default"])
